# Generated by Django 3.2.6 on 2021-08-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='krishivdemy_app.month'),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='krishivdemy_app.year'),
        ),
    ]
