# Generated by Django 3.2.6 on 2021-08-11 22:28

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0004_text_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='krishivdemy_app.page')),
            ],
        ),
    ]
