# Generated by Django 3.2.6 on 2021-08-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
