# Generated by Django 3.2.6 on 2021-08-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='krishivdemy_app.page'),
        ),
    ]
