# Generated by Django 3.2.6 on 2021-08-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0007_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(default='link', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.CharField(default='text', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='video', max_length=7, null=True),
        ),
    ]
