# Generated by Django 3.2.6 on 2021-08-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0009_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
