# Generated by Django 3.2.6 on 2021-08-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishivdemy_app', '0010_auto_20210811_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
